// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgfcpq0UJASyFgzS-P4P0IpYwQQrdGv_A',
    appId: '1:680902184651:web:4a0d6ea731897cff2d954e',
    messagingSenderId: '680902184651',
    projectId: 'codepur-97296',
    authDomain: 'codepur-97296.firebaseapp.com',
    storageBucket: 'codepur-97296.appspot.com',
    measurementId: 'G-1DMS8VNRMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkzlkOqipOGT09y3-MQfG9pIfU4fOsEYc',
    appId: '1:680902184651:android:10ccc6d08480f0342d954e',
    messagingSenderId: '680902184651',
    projectId: 'codepur-97296',
    storageBucket: 'codepur-97296.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaUi0MwaW0JdXpK9-Wip1gmNZQ69tK33o',
    appId: '1:680902184651:ios:570498c61a5294b52d954e',
    messagingSenderId: '680902184651',
    projectId: 'codepur-97296',
    storageBucket: 'codepur-97296.appspot.com',
    iosBundleId: 'com.example.codepur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaUi0MwaW0JdXpK9-Wip1gmNZQ69tK33o',
    appId: '1:680902184651:ios:2f1d37cdf149d7962d954e',
    messagingSenderId: '680902184651',
    projectId: 'codepur-97296',
    storageBucket: 'codepur-97296.appspot.com',
    iosBundleId: 'com.example.codepur.RunnerTests',
  );
}
